<h1>Top Rated Movie</h1>
<span style="font-size: 0.98rem; color: gray">Using API calling from <a href="https://developer.themoviedb.org/reference/guest-session-rated-movies"> TMDB </a></span>

In [ ]:
import os
import pandas as pd
import requests
from dotenv import load_dotenv

In [ ]:
load_dotenv()

True

In [ ]:
API_KEY = os.getenv("TMDB_API_KEY")

In [ ]:
data_list = []

In [ ]:
url = "https://api.themoviedb.org/3/movie/top_rated"

params = {
    "api_key": API_KEY,
    "language": "en-US",
    "page": 1,
}

response = requests.get(url, params=params, timeout=15)
response.raise_for_status()

In [ ]:
data = response.json()
total_pages = min(data["total_pages"],500)

for page in range(1, total_pages+1):
    params["page"] = page

    response = requests.get(url, params=params, timeout=15)
    response.raise_for_status()

    data_list.extend(response.json()["results"])

df = pd.DataFrame(data_list)

df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg,"[16, 28, 12, 18]",1560520,Batman: Knightfall Part 1: Knightfall,en,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",40.4759,/360qdtu2hLnqMu8SVHMywn420w1.jpg,2026-06-23,False,False,9.100,475
1,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 12, 14, 28]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",66.8911,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.045,1364
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",48.3453,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.847,2264
3,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,12.4249,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.823,403
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,51.5936,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.800,2317

In [ ]:
df.columns

Index(['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average',
       'vote_count'],
      dtype='str')

In [ ]:
columns = ["id", "title", "overview", "release_date", "popularity", "vote_average", "vote_count"]
df = df[columns]

df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,40.4759,9.100,475
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,66.8911,9.045,1364
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,48.3453,8.847,2264
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.4249,8.823,403
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,51.5936,8.800,2317

In [ ]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]} \n")

print(f"Check for null values\n{df.isnull().sum()}\n")
print(f"Check for duplicated values\n{df.duplicated().sum()}")

Rows: 10000
Columns: 7

Check for null values
id              0
title           0
overview        0
release_date    0
popularity      0
vote_average    0
vote_count      0
dtype: int64

Check for duplicated values
2

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   title         10000 non-null  str
 2   overview      10000 non-null  str
 3   release_date  10000 non-null  str
 4   popularity    10000 non-null  float64
 5   vote_average  10000 non-null  float64
 6   vote_count    10000 non-null  int64
dtypes: float64(2), int64(2), str(3)
memory usage: 547.0 KB

In [ ]:
df.describe()

                 id    popularity  vote_average    vote_count
count  1.000000e+04  10000.000000  10000.000000  10000.000000
mean   2.431877e+05      9.563238      6.804293   2182.743300
std    3.265331e+05     22.939005      0.614199   3502.240038
min    2.000000e+00      0.008200      5.700000    300.000000
25%    1.044850e+04      4.463300      6.304000    480.000000
50%    4.391200e+04      6.523600      6.770000    885.000000
75%    4.265605e+05     10.482825      7.252000   2201.250000
max    1.632181e+06   1571.738800      9.100000  41577.000000

### 1. Find the 10 highest-rated movies

In [ ]:
df.sort_values("vote_average", ascending=False)[["title", "vote_average", "vote_count"]].head(10)

                                            title  vote_average  vote_count
0           Batman: Knightfall Part 1: Knightfall         9.100         475
1                 Avatar Aang: The Last Airbender         9.045        1364
2                                         Swapped         8.847        2264
3                             Accidental Partners         8.823         403
4  Demon Slayer: Kimetsu no Yaiba Infinity Castle         8.800        2317
5                                 Facing El Chapo         8.778         950
6                        The Shawshank Redemption         8.733       31636
7                                   The Godfather         8.689       23807
8                               Project Hail Mary         8.635        8414
9                                         Michael         8.603        4604

### 2. Find the 10 most vosted movies

In [ ]:
df.sort_values("vote_count", ascending=False)[["title", "vote_average", "vote_count"]].head(10)

                         title  vote_average  vote_count
22                Interstellar         8.491       41577
55                   Inception         8.373       40502
222               The Avengers         8.081       40108
16             The Dark Knight         8.538       37028
1077                    Avatar         7.600       34887
1030                  Deadpool         7.626       33495
105     Avengers: Infinity War         8.200       33212
35                  Fight Club         8.438       33075
6     The Shawshank Redemption         8.733       31636
24                Pulp Fiction         8.481       31139

### 3. Find the average movie-rating

In [ ]:
df["vote_average"].mean()

np.float64(6.804292600000001)

### 4. Check the most common release year

In [ ]:
pd.to_datetime(df['release_date'], errors='coerce').dt.year.value_counts().head(10)

release_date
2019.0    394
2018.0    387
2017.0    367
2014.0    349
2016.0    342
2021.0    334
2022.0    327
2015.0    324
2013.0    316
2020.0    309
Name: count, dtype: int64